export default {
    navbarTextColor: "#B5BDFB",
    navbarBackgroundColor: "#465DEF",
    taskSidebarBorder: "1px solid #E6EBF1",
    secondaryLightColor: "#F6F9FC",
    primaryLightColor: "#FFF",
    mainBackgroundColor: "#E6EBF1",
    buttonGreen: "#39C3797E",
    buttonGreenHover: "#39C379",
    buttonPurple: "#ad14c4",
    buttonPurpleHover: "#712aa3",
    buttonOrange: "#EB9771",
    buttonOrangeHover: "#FF7325",
    buttonAltRed: "#FE716C",
    buttonBlue: "#5D6CED",
    buttonBlueHover: "#4457F3",
    iconPrimaryColor: "#838DAC",
    fontInitalColor: "#000",
    fontBlurredColor: "#838EAB",
    primaryBoxShadow: "0px 7px 14px #32325D1A",
    focusedBackgroundColor: "#fafafa"
}
