export default {
    navbarTextColor: "#B5BDFB",
    navbarBackgroundColor: "#465DEF",
    taskSidebarBorder: "1px solid #E6EBF1",
    secondaryLightColor: "#F6F9FC",
    primaryLightColor: "#FFF",
    mainBackgroundColor: "#E6EBF1",
    buttonGreen: "hsla(148, 55%, 49%, .5)",
    buttonGreenHover: "#39C379",
    buttonPurple: "#ad14c4",
    buttonPurpleHover: "#712aa3",
    buttonOrange: "#EB9771",
    buttonOrangeHover: "#FF7325",
    buttonAltRed: "#FE716C",
    buttonBlue: "#5D6CED",
    buttonBlueHover: "#4457F3",
    iconPrimaryColor: "#838DAC",
    fontInitalColor: "#000",
    fontBlurredColor: "#838EAB",
    primaryBoxShadow: "0px 7px 14px hsla(240, 30%, 28%, .1)",
    focusedBackgroundColor: "#fafafa",
    programmingLangBackgroundColor: "#D7D0F0",
    programmingLangTextColor: "#5D47AA",
    buttonGray: "#8F9DBE",
    buttonGrayHover: "#7082a5"
}
